[uWSGI] getting INI configuration from cmdb_uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Sun Apr  5 15:26:56 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 08 December 2019 05:05:53
os: Linux-3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019
nodename: fushisanlang.cn
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/python/flask/cmdb
detected binary path: /usr/local/bin/uwsgi
your processes number limit is 7270
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:30005 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:46708 (port auto-assigned) fd 3
Python version: 3.6.8 (default, Aug  7 2019, 17:28:10)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x12e94b0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
added /home/python/flask/cmdb/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x12e94b0 pid: 29975 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 29975)
spawned uWSGI worker 1 (pid: 29988, cores: 1)
spawned uWSGI http 1 (pid: 29989)
gateway "uWSGI http 1" has been buried (pid: 29989)
...brutally killing workers...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/python/flask/cmdb
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:46708)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from cmdb_uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Sun Apr  5 15:27:14 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 08 December 2019 05:05:53
os: Linux-3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019
nodename: fushisanlang.cn
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/python/flask/cmdb
detected binary path: /usr/local/bin/uwsgi
your processes number limit is 7270
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:30005 fd 5
uwsgi socket 0 bound to TCP address 127.0.0.1:36972 (port auto-assigned) fd 4
Python version: 3.6.8 (default, Aug  7 2019, 17:28:10)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1334430
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
added /home/python/flask/cmdb/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1334430 pid: 29975 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 29975)
spawned uWSGI worker 1 (pid: 30017, cores: 1)
spawned uWSGI http 1 (pid: 30018)
Sun Apr  5 15:27:24 2020 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
[uWSGI] getting INI configuration from cmdb_uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Sun Apr  5 15:27:36 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 08 December 2019 05:05:53
os: Linux-3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019
nodename: fushisanlang.cn
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/python/flask/cmdb
detected binary path: /usr/local/bin/uwsgi
your processes number limit is 7270
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:30005 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:46254 (port auto-assigned) fd 3
Python version: 3.6.8 (default, Aug  7 2019, 17:28:10)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x11eb4b0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
added /home/python/flask/cmdb/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x11eb4b0 pid: 30050 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 30050)
spawned uWSGI worker 1 (pid: 30065, cores: 1)
spawned uWSGI http 1 (pid: 30068)
[pid: 30065|app: 0|req: 1/1] 127.0.0.1 () {52 vars in 933 bytes} [Sun Apr  5 15:28:23 2020] GET / => generated 1954 bytes in 182 msecs (HTTP/1.0 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 30065|app: 0|req: 2/2] 127.0.0.1 () {52 vars in 880 bytes} [Sun Apr  5 15:28:24 2020] GET /favicon.ico => generated 232 bytes in 34 msecs (HTTP/1.0 404) 2 headers in 72 bytes (1 switches on core 0)
[pid: 30065|app: 0|req: 3/3] 127.0.0.1 () {52 vars in 994 bytes} [Sun Apr  5 15:28:27 2020] GET /page_update_register => generated 232 bytes in 0 msecs (HTTP/1.0 404) 2 headers in 72 bytes (1 switches on core 0)
[pid: 30065|app: 0|req: 4/4] 127.0.0.1 () {52 vars in 968 bytes} [Sun Apr  5 15:28:31 2020] GET /add_env => generated 3963 bytes in 2 msecs (HTTP/1.0 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 30065|app: 0|req: 5/5] 127.0.0.1 () {52 vars in 931 bytes} [Tue Apr  7 15:32:06 2020] GET / => generated 1954 bytes in 138 msecs (HTTP/1.0 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 30065|app: 0|req: 6/6] 127.0.0.1 () {52 vars in 878 bytes} [Tue Apr  7 15:32:06 2020] GET /favicon.ico => generated 232 bytes in 0 msecs (HTTP/1.0 404) 2 headers in 72 bytes (1 switches on core 0)
Fri Apr 24 14:38:51 2020 - *** /home/python/flask/cmdb has been touched... grace them all !!! ***
gateway "uWSGI http 1" has been buried (pid: 30068)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 30065)...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/python/flask/cmdb
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:46254)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from cmdb_uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Fri Apr 24 14:38:53 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 08 December 2019 05:05:53
os: Linux-3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019
nodename: fushisanlang.cn
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/python/flask/cmdb
detected binary path: /usr/local/bin/uwsgi
your processes number limit is 7270
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:30005 fd 5
uwsgi socket 0 bound to TCP address 127.0.0.1:41789 (port auto-assigned) fd 4
Python version: 3.6.8 (default, Aug  7 2019, 17:28:10)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x15ab430
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
added /home/python/flask/cmdb/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x15ab430 pid: 30050 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 30050)
spawned uWSGI worker 1 (pid: 29337, cores: 1)
spawned uWSGI http 1 (pid: 29338)
Wed Apr 29 11:29:11 2020 - *** /home/python/flask/cmdb has been touched... grace them all !!! ***
gateway "uWSGI http 1" has been buried (pid: 29338)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 29337)...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/python/flask/cmdb
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 4 mapped to socket 0 (127.0.0.1:41789)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from cmdb_uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Wed Apr 29 11:29:12 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 08 December 2019 05:05:53
os: Linux-3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019
nodename: fushisanlang.cn
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/python/flask/cmdb
detected binary path: /usr/local/bin/uwsgi
your processes number limit is 7270
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:30005 fd 5
uwsgi socket 0 bound to TCP address 127.0.0.1:41401 (port auto-assigned) fd 3
Python version: 3.6.8 (default, Aug  7 2019, 17:28:10)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1404430
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
added /home/python/flask/cmdb/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1404430 pid: 30050 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 30050)
spawned uWSGI worker 1 (pid: 21355, cores: 1)
spawned uWSGI http 1 (pid: 21356)
Wed Apr 29 11:29:13 2020 - *** /home/python/flask/cmdb has been touched... grace them all !!! ***
gateway "uWSGI http 1" has been buried (pid: 21356)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 21355)...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/python/flask/cmdb
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:41401)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from cmdb_uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Wed Apr 29 11:29:14 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 08 December 2019 05:05:53
os: Linux-3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019
nodename: fushisanlang.cn
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/python/flask/cmdb
detected binary path: /usr/local/bin/uwsgi
your processes number limit is 7270
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:30005 fd 5
uwsgi socket 0 bound to TCP address 127.0.0.1:46586 (port auto-assigned) fd 4
Python version: 3.6.8 (default, Aug  7 2019, 17:28:10)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1de3430
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
added /home/python/flask/cmdb/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1de3430 pid: 30050 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 30050)
spawned uWSGI worker 1 (pid: 21361, cores: 1)
spawned uWSGI http 1 (pid: 21362)
[pid: 21361|app: 0|req: 1/1] 127.0.0.1 () {50 vars in 889 bytes} [Wed Apr 29 11:29:30 2020] GET / => generated 1954 bytes in 117 msecs (HTTP/1.0 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 21361|app: 0|req: 2/2] 127.0.0.1 () {50 vars in 836 bytes} [Wed Apr 29 11:29:30 2020] GET /favicon.ico => generated 232 bytes in 10 msecs (HTTP/1.0 404) 2 headers in 72 bytes (1 switches on core 0)
[pid: 21361|app: 0|req: 3/3] 127.0.0.1 () {50 vars in 940 bytes} [Wed Apr 29 11:29:34 2020] GET /update_register => generated 4283 bytes in 11 msecs (HTTP/1.0 200) 2 headers in 81 bytes (1 switches on core 0)
[2020-04-29 11:29:37,011] ERROR in app: Exception on /update_register_over [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/python/flask/cmdb/app.py", line 96, in update_register_over
    update_operaction("page",page_update_str,page_update_key_str)
  File "/home/python/flask/cmdb/operate_data.py", line 49, in update_operaction
    cursor.execute(sql)
  File "/usr/local/lib/python3.6/site-packages/mysql/connector/cursor.py", line 551, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/usr/local/lib/python3.6/site-packages/mysql/connector/connection.py", line 490, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/usr/local/lib/python3.6/site-packages/mysql/connector/connection.py", line 395, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '                                         ' at line 1
[pid: 21361|app: 0|req: 4/4] 127.0.0.1 () {58 vars in 1110 bytes} [Wed Apr 29 11:29:37 2020] POST /update_register_over => generated 290 bytes in 60 msecs (HTTP/1.0 500) 2 headers in 84 bytes (1 switches on core 0)
[pid: 21361|app: 0|req: 5/5] 127.0.0.1 () {50 vars in 889 bytes} [Wed Apr 29 11:29:39 2020] GET / => generated 1954 bytes in 2 msecs (HTTP/1.0 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 21361|app: 0|req: 6/6] 127.0.0.1 () {50 vars in 889 bytes} [Wed Apr 29 11:29:39 2020] GET / => generated 1954 bytes in 2 msecs (HTTP/1.0 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 21361|app: 0|req: 7/7] 127.0.0.1 () {50 vars in 889 bytes} [Wed Apr 29 11:29:40 2020] GET / => generated 1954 bytes in 2 msecs (HTTP/1.0 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 21361|app: 0|req: 8/8] 127.0.0.1 () {50 vars in 889 bytes} [Wed Apr 29 11:29:40 2020] GET / => generated 1954 bytes in 2 msecs (HTTP/1.0 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 21361|app: 0|req: 9/9] 127.0.0.1 () {50 vars in 889 bytes} [Wed Apr 29 11:29:40 2020] GET / => generated 1954 bytes in 2 msecs (HTTP/1.0 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 21361|app: 0|req: 10/10] 127.0.0.1 () {50 vars in 924 bytes} [Wed Apr 29 11:29:44 2020] GET /add_env => generated 3963 bytes in 15 msecs (HTTP/1.0 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 21361|app: 0|req: 11/11] 127.0.0.1 () {58 vars in 1086 bytes} [Wed Apr 29 11:30:36 2020] POST /add_env_over => generated 188 bytes in 32 msecs (HTTP/1.0 200) 2 headers in 80 bytes (1 switches on core 0)
[pid: 21361|app: 0|req: 12/12] 127.0.0.1 () {50 vars in 922 bytes} [Wed Apr 29 11:30:37 2020] GET / => generated 2336 bytes in 2 msecs (HTTP/1.0 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 21361|app: 0|req: 13/13] 127.0.0.1 () {50 vars in 950 bytes} [Wed Apr 29 11:30:43 2020] GET /page_update_register => generated 232 bytes in 0 msecs (HTTP/1.0 404) 2 headers in 72 bytes (1 switches on core 0)
[pid: 21361|app: 0|req: 14/14] 127.0.0.1 () {50 vars in 940 bytes} [Wed Apr 29 11:30:47 2020] GET /update_register => generated 4328 bytes in 2 msecs (HTTP/1.0 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 21361|app: 0|req: 15/15] 127.0.0.1 () {58 vars in 1110 bytes} [Wed Apr 29 11:31:05 2020] POST /update_register_over => generated 193 bytes in 27 msecs (HTTP/1.0 200) 2 headers in 80 bytes (1 switches on core 0)
[pid: 21361|app: 0|req: 16/16] 127.0.0.1 () {50 vars in 930 bytes} [Wed Apr 29 11:31:06 2020] GET / => generated 2295 bytes in 2 msecs (HTTP/1.0 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 21361|app: 0|req: 17/17] 127.0.0.1 () {50 vars in 950 bytes} [Wed Apr 29 11:31:08 2020] GET /page_update_register => generated 232 bytes in 0 msecs (HTTP/1.0 404) 2 headers in 72 bytes (1 switches on core 0)
[pid: 21361|app: 0|req: 18/18] 127.0.0.1 () {50 vars in 954 bytes} [Wed Apr 29 11:31:09 2020] GET /system_update_register => generated 232 bytes in 0 msecs (HTTP/1.0 404) 2 headers in 72 bytes (1 switches on core 0)
[uWSGI] getting INI configuration from cmdb_uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Mon May 18 18:50:34 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 08 December 2019 05:05:53
os: Linux-3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019
nodename: fushisanlang.cn
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/python/flask/cmdb
detected binary path: /usr/local/bin/uwsgi
your processes number limit is 7270
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:30005 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:37505 (port auto-assigned) fd 3
Python version: 3.6.8 (default, Aug  7 2019, 17:28:10)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1ae44b0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
added /home/python/flask/cmdb/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1ae44b0 pid: 16248 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 16248)
spawned uWSGI worker 1 (pid: 16262, cores: 1)
spawned uWSGI http 1 (pid: 16263)
gateway "uWSGI http 1" has been buried (pid: 16263)
...brutally killing workers...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/python/flask/cmdb
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:37505)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from cmdb_uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Mon May 18 18:55:38 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 08 December 2019 05:05:53
os: Linux-3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019
nodename: fushisanlang.cn
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/python/flask/cmdb
detected binary path: /usr/local/bin/uwsgi
your processes number limit is 7270
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:30005 fd 5
uwsgi socket 0 bound to TCP address 127.0.0.1:38697 (port auto-assigned) fd 4
Python version: 3.6.8 (default, Aug  7 2019, 17:28:10)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x22af430
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
added /home/python/flask/cmdb/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x22af430 pid: 16248 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 16248)
spawned uWSGI worker 1 (pid: 16657, cores: 1)
spawned uWSGI http 1 (pid: 16658)
Mon May 18 18:55:48 2020 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
[uWSGI] getting INI configuration from cmdb_uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Mon May 18 18:56:02 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 08 December 2019 05:05:53
os: Linux-3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019
nodename: fushisanlang.cn
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/python/flask/cmdb
detected binary path: /usr/local/bin/uwsgi
your processes number limit is 7270
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:30005 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:41824 (port auto-assigned) fd 3
Python version: 3.6.8 (default, Aug  7 2019, 17:28:10)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1c0c4b0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
added /home/python/flask/cmdb/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1c0c4b0 pid: 16699 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 16699)
spawned uWSGI worker 1 (pid: 16717, cores: 1)
spawned uWSGI http 1 (pid: 16718)
Wed May 20 03:34:27 2020 - *** /home/python/flask/cmdb has been touched... grace them all !!! ***
gateway "uWSGI http 1" has been buried (pid: 16718)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 16717)...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/python/flask/cmdb
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:41824)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from cmdb_uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Wed May 20 03:34:28 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 08 December 2019 05:05:53
os: Linux-3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019
nodename: fushisanlang.cn
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/python/flask/cmdb
detected binary path: /usr/local/bin/uwsgi
your processes number limit is 7270
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:30005 fd 5
uwsgi socket 0 bound to TCP address 127.0.0.1:36530 (port auto-assigned) fd 4
Python version: 3.6.8 (default, Aug  7 2019, 17:28:10)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1d0b430
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
added /home/python/flask/cmdb/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1d0b430 pid: 16699 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 16699)
spawned uWSGI worker 1 (pid: 17474, cores: 1)
spawned uWSGI http 1 (pid: 17475)
Wed May 20 03:35:05 2020 - *** /home/python/flask/cmdb has been touched... grace them all !!! ***
gateway "uWSGI http 1" has been buried (pid: 17475)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 17474)...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/python/flask/cmdb
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 4 mapped to socket 0 (127.0.0.1:36530)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from cmdb_uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Wed May 20 03:35:06 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 08 December 2019 05:05:53
os: Linux-3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019
nodename: fushisanlang.cn
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/python/flask/cmdb
detected binary path: /usr/local/bin/uwsgi
your processes number limit is 7270
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:30005 fd 5
uwsgi socket 0 bound to TCP address 127.0.0.1:35352 (port auto-assigned) fd 3
Python version: 3.6.8 (default, Aug  7 2019, 17:28:10)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x816430
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
added /home/python/flask/cmdb/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x816430 pid: 16699 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 16699)
spawned uWSGI worker 1 (pid: 17513, cores: 1)
spawned uWSGI http 1 (pid: 17514)
Wed May 20 05:12:00 2020 - *** /home/python/flask/cmdb has been touched... grace them all !!! ***
gateway "uWSGI http 1" has been buried (pid: 17514)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 17513)...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/python/flask/cmdb
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:35352)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from cmdb_uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Wed May 20 05:12:01 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 08 December 2019 05:05:53
os: Linux-3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019
nodename: fushisanlang.cn
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/python/flask/cmdb
detected binary path: /usr/local/bin/uwsgi
your processes number limit is 7270
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:30005 fd 5
uwsgi socket 0 bound to TCP address 127.0.0.1:46807 (port auto-assigned) fd 4
Python version: 3.6.8 (default, Aug  7 2019, 17:28:10)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1735430
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
added /home/python/flask/cmdb/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1735430 pid: 16699 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 16699)
spawned uWSGI worker 1 (pid: 23493, cores: 1)
spawned uWSGI http 1 (pid: 23494)
Wed May 20 05:12:36 2020 - *** /home/python/flask/cmdb has been touched... grace them all !!! ***
gateway "uWSGI http 1" has been buried (pid: 23494)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 23493)...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/python/flask/cmdb
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 4 mapped to socket 0 (127.0.0.1:46807)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from cmdb_uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Wed May 20 05:12:37 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 08 December 2019 05:05:53
os: Linux-3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019
nodename: fushisanlang.cn
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/python/flask/cmdb
detected binary path: /usr/local/bin/uwsgi
your processes number limit is 7270
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:30005 fd 5
uwsgi socket 0 bound to TCP address 127.0.0.1:36792 (port auto-assigned) fd 3
Python version: 3.6.8 (default, Aug  7 2019, 17:28:10)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x20b5430
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
added /home/python/flask/cmdb/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x20b5430 pid: 16699 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 16699)
spawned uWSGI worker 1 (pid: 23531, cores: 1)
spawned uWSGI http 1 (pid: 23532)
Wed May 20 05:13:50 2020 - *** /home/python/flask/cmdb has been touched... grace them all !!! ***
gateway "uWSGI http 1" has been buried (pid: 23532)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 23531)...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/python/flask/cmdb
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:36792)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from cmdb_uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Wed May 20 05:13:51 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 08 December 2019 05:05:53
os: Linux-3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019
nodename: fushisanlang.cn
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/python/flask/cmdb
detected binary path: /usr/local/bin/uwsgi
your processes number limit is 7270
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:30005 fd 5
uwsgi socket 0 bound to TCP address 127.0.0.1:38401 (port auto-assigned) fd 4
Python version: 3.6.8 (default, Aug  7 2019, 17:28:10)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xb31430
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
added /home/python/flask/cmdb/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xb31430 pid: 16699 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 16699)
spawned uWSGI worker 1 (pid: 23612, cores: 1)
spawned uWSGI http 1 (pid: 23613)
Wed May 20 05:14:02 2020 - *** /home/python/flask/cmdb has been touched... grace them all !!! ***
gateway "uWSGI http 1" has been buried (pid: 23613)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 23612)...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/python/flask/cmdb
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 4 mapped to socket 0 (127.0.0.1:38401)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from cmdb_uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Wed May 20 05:14:03 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 08 December 2019 05:05:53
os: Linux-3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019
nodename: fushisanlang.cn
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/python/flask/cmdb
detected binary path: /usr/local/bin/uwsgi
your processes number limit is 7270
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:30005 fd 5
uwsgi socket 0 bound to TCP address 127.0.0.1:40365 (port auto-assigned) fd 3
Python version: 3.6.8 (default, Aug  7 2019, 17:28:10)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1793430
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
added /home/python/flask/cmdb/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1793430 pid: 16699 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 16699)
spawned uWSGI worker 1 (pid: 23626, cores: 1)
spawned uWSGI http 1 (pid: 23627)
gateway "uWSGI http 1" has been buried (pid: 23627)
...brutally killing workers...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/python/flask/cmdb
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:40365)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from cmdb_uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Wed May 20 05:14:12 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 08 December 2019 05:05:53
os: Linux-3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019
nodename: fushisanlang.cn
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/python/flask/cmdb
detected binary path: /usr/local/bin/uwsgi
your processes number limit is 7270
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:30005 fd 5
uwsgi socket 0 bound to TCP address 127.0.0.1:37790 (port auto-assigned) fd 4
Python version: 3.6.8 (default, Aug  7 2019, 17:28:10)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xeaf430
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
added /home/python/flask/cmdb/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xeaf430 pid: 16699 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 16699)
spawned uWSGI worker 1 (pid: 23660, cores: 1)
spawned uWSGI http 1 (pid: 23661)
Wed May 20 05:14:21 2020 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
[uWSGI] getting INI configuration from cmdb_uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Wed May 20 05:14:22 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 08 December 2019 05:05:53
os: Linux-3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019
nodename: fushisanlang.cn
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/python/flask/cmdb
detected binary path: /usr/local/bin/uwsgi
your processes number limit is 7270
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:30005 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:36631 (port auto-assigned) fd 3
Python version: 3.6.8 (default, Aug  7 2019, 17:28:10)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x11c14b0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
added /home/python/flask/cmdb/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x11c14b0 pid: 23672 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 23672)
spawned uWSGI worker 1 (pid: 23675, cores: 1)
spawned uWSGI http 1 (pid: 23676)
Wed May 20 05:14:56 2020 - *** /home/python/flask/cmdb has been touched... grace them all !!! ***
gateway "uWSGI http 1" has been buried (pid: 23676)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 23675)...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/python/flask/cmdb
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:36631)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from cmdb_uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Wed May 20 05:14:57 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 08 December 2019 05:05:53
os: Linux-3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019
nodename: fushisanlang.cn
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/python/flask/cmdb
detected binary path: /usr/local/bin/uwsgi
your processes number limit is 7270
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:30005 fd 5
uwsgi socket 0 bound to TCP address 127.0.0.1:34252 (port auto-assigned) fd 4
Python version: 3.6.8 (default, Aug  7 2019, 17:28:10)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x853430
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
added /home/python/flask/cmdb/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x853430 pid: 23672 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 23672)
spawned uWSGI worker 1 (pid: 23718, cores: 1)
spawned uWSGI http 1 (pid: 23719)
Wed May 20 05:14:58 2020 - *** /home/python/flask/cmdb has been touched... grace them all !!! ***
gateway "uWSGI http 1" has been buried (pid: 23719)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 23718)...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/python/flask/cmdb
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 4 mapped to socket 0 (127.0.0.1:34252)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from cmdb_uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Wed May 20 05:14:59 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 08 December 2019 05:05:53
os: Linux-3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019
nodename: fushisanlang.cn
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/python/flask/cmdb
detected binary path: /usr/local/bin/uwsgi
your processes number limit is 7270
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:30005 fd 5
uwsgi socket 0 bound to TCP address 127.0.0.1:33175 (port auto-assigned) fd 3
Python version: 3.6.8 (default, Aug  7 2019, 17:28:10)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1a9e430
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
added /home/python/flask/cmdb/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1a9e430 pid: 23672 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 23672)
spawned uWSGI worker 1 (pid: 23723, cores: 1)
spawned uWSGI http 1 (pid: 23724)
[('aaaaaaasdf', 'aaa', 'aaa', 'aaa', '123', '123', '2020-04-05', '123123', '123', '123', 'aaa', '2020-04-05'), ('asdfsadf', 'sadfsadf', 'sdfasadf', 'sadfsadf', 'sdfsdaf', 'sadfsadf', '2020-04-03', 'sadfsadf', 'sdafsadf', 'sadfsda', 'sfadfasd', '2020-04-03'), ('sadfsadfsadf', 'asfsdaf', 'sadfsadf', 'sadfsadf', 'asdfsadf', 'safsdaf', '2020-04-03', 'asfsadf', 'sadfsad', 'sadfsdaf', 'safsdf', '2020-04-03'), ('吉林省高院', 'jilinXXXX', '123123213', '0431-12368', '', '', '2020-04-29', '12312321312', 'wrweqrqwrw', '1.5.1', 'shandongPr', '2020-04-29')]
[pid: 23723|app: 0|req: 1/1] 127.0.0.1 () {28 vars in 298 bytes} [Wed May 20 05:15:08 2020] GET / => generated 2295 bytes in 19 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
Wed May 20 05:17:26 2020 - *** /home/python/flask/cmdb has been touched... grace them all !!! ***
gateway "uWSGI http 1" has been buried (pid: 23724)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 23723)...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/python/flask/cmdb
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:33175)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from cmdb_uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Wed May 20 05:17:27 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 08 December 2019 05:05:53
os: Linux-3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019
nodename: fushisanlang.cn
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/python/flask/cmdb
detected binary path: /usr/local/bin/uwsgi
your processes number limit is 7270
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:30005 fd 5
uwsgi socket 0 bound to TCP address 127.0.0.1:42980 (port auto-assigned) fd 4
Python version: 3.6.8 (default, Aug  7 2019, 17:28:10)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x16ff430
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
added /home/python/flask/cmdb/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x16ff430 pid: 23672 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 23672)
spawned uWSGI worker 1 (pid: 23874, cores: 1)
spawned uWSGI http 1 (pid: 23875)
Wed May 20 07:28:48 2020 - *** /home/python/flask/cmdb has been touched... grace them all !!! ***
gateway "uWSGI http 1" has been buried (pid: 23875)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 23874)...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/python/flask/cmdb
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 4 mapped to socket 0 (127.0.0.1:42980)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from cmdb_uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Wed May 20 07:28:49 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 08 December 2019 05:05:53
os: Linux-3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019
nodename: fushisanlang.cn
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/python/flask/cmdb
detected binary path: /usr/local/bin/uwsgi
your processes number limit is 7270
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:30005 fd 5
uwsgi socket 0 bound to TCP address 127.0.0.1:34117 (port auto-assigned) fd 3
Python version: 3.6.8 (default, Aug  7 2019, 17:28:10)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1521430
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
added /home/python/flask/cmdb/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1521430 pid: 23672 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 23672)
spawned uWSGI worker 1 (pid: 31863, cores: 1)
spawned uWSGI http 1 (pid: 31864)
gateway "uWSGI http 1" has been buried (pid: 31864)
...brutally killing workers...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/python/flask/cmdb
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:34117)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from cmdb_uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Fri May 22 20:38:32 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 08 December 2019 05:05:53
os: Linux-3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019
nodename: fushisanlang.cn
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/python/flask/cmdb
detected binary path: /usr/local/bin/uwsgi
your processes number limit is 7270
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:30005 fd 5
uwsgi socket 0 bound to TCP address 127.0.0.1:45989 (port auto-assigned) fd 4
Python version: 3.6.8 (default, Aug  7 2019, 17:28:10)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x9fc430
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
added /home/python/flask/cmdb/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x9fc430 pid: 23672 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 23672)
spawned uWSGI worker 1 (pid: 22646, cores: 1)
spawned uWSGI http 1 (pid: 22647)
Fri May 22 20:38:41 2020 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
[uWSGI] getting INI configuration from cmdb_uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Fri May 22 20:39:04 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 08 December 2019 05:05:53
os: Linux-3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019
nodename: fushisanlang.cn
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/python/flask/cmdb
detected binary path: /usr/local/bin/uwsgi
your processes number limit is 7270
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:30005 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:34206 (port auto-assigned) fd 3
Python version: 3.6.8 (default, Aug  7 2019, 17:28:10)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xc984b0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
added /home/python/flask/cmdb/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xc984b0 pid: 22700 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 22700)
spawned uWSGI worker 1 (pid: 22713, cores: 1)
spawned uWSGI http 1 (pid: 22718)
gateway "uWSGI http 1" has been buried (pid: 22718)
...brutally killing workers...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/python/flask/cmdb
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:34206)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from cmdb_uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Fri May 22 20:39:44 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 08 December 2019 05:05:53
os: Linux-3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019
nodename: fushisanlang.cn
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/python/flask/cmdb
detected binary path: /usr/local/bin/uwsgi
your processes number limit is 7270
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:30005 fd 5
uwsgi socket 0 bound to TCP address 127.0.0.1:33217 (port auto-assigned) fd 4
Python version: 3.6.8 (default, Aug  7 2019, 17:28:10)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x19a0430
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
added /home/python/flask/cmdb/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x19a0430 pid: 22700 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 22700)
spawned uWSGI worker 1 (pid: 22773, cores: 1)
spawned uWSGI http 1 (pid: 22774)
Fri May 22 20:39:54 2020 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
[uWSGI] getting INI configuration from cmdb_uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Fri May 22 20:40:17 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 08 December 2019 05:05:53
os: Linux-3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019
nodename: fushisanlang.cn
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/python/flask/cmdb
detected binary path: /usr/local/bin/uwsgi
your processes number limit is 7270
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:30005 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:43364 (port auto-assigned) fd 3
Python version: 3.6.8 (default, Aug  7 2019, 17:28:10)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x26f94b0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
added /home/python/flask/cmdb/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x26f94b0 pid: 22832 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 22832)
spawned uWSGI worker 1 (pid: 22852, cores: 1)
spawned uWSGI http 1 (pid: 22853)
Wed Aug 19 09:55:25 2020 - *** /home/python/flask/cmdb has been touched... grace them all !!! ***
gateway "uWSGI http 1" has been buried (pid: 22853)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 22852)...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/python/flask/cmdb
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:43364)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from cmdb_uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Wed Aug 19 09:55:26 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 08 December 2019 05:05:53
os: Linux-3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019
nodename: fushisanlang.cn
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/python/flask/cmdb
detected binary path: /usr/local/bin/uwsgi
your processes number limit is 7270
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:30005 fd 5
uwsgi socket 0 bound to TCP address 127.0.0.1:39168 (port auto-assigned) fd 4
Python version: 3.6.8 (default, Aug  7 2019, 17:28:10)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x18ea430
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
added /home/python/flask/cmdb/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x18ea430 pid: 22832 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 22832)
spawned uWSGI worker 1 (pid: 3756, cores: 1)
spawned uWSGI http 1 (pid: 3757)
Wed Aug 19 09:55:31 2020 - *** /home/python/flask/cmdb has been touched... grace them all !!! ***
gateway "uWSGI http 1" has been buried (pid: 3757)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 3756)...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/python/flask/cmdb
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 4 mapped to socket 0 (127.0.0.1:39168)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from cmdb_uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Wed Aug 19 09:55:32 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 08 December 2019 05:05:53
os: Linux-3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019
nodename: fushisanlang.cn
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/python/flask/cmdb
detected binary path: /usr/local/bin/uwsgi
your processes number limit is 7270
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:30005 fd 5
uwsgi socket 0 bound to TCP address 127.0.0.1:45919 (port auto-assigned) fd 3
Python version: 3.6.8 (default, Aug  7 2019, 17:28:10)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x8c8430
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
added /home/python/flask/cmdb/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x8c8430 pid: 22832 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 22832)
spawned uWSGI worker 1 (pid: 3765, cores: 1)
spawned uWSGI http 1 (pid: 3766)
[uWSGI] getting INI configuration from cmdb_uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Thu Nov 12 09:15:00 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 08 December 2019 05:05:53
os: Linux-3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019
nodename: fushisanlang.cn
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/python/flask/cmdb
detected binary path: /usr/local/bin/uwsgi
your processes number limit is 6945
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:30005 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:40282 (port auto-assigned) fd 3
Python version: 3.6.8 (default, Aug  7 2019, 17:28:10)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xbb84b0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
added /home/python/flask/cmdb/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0xbb84b0 pid: 839 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 839)
spawned uWSGI worker 1 (pid: 1243, cores: 1)
spawned uWSGI http 1 (pid: 1244)
gateway "uWSGI http 1" has been buried (pid: 1244)
...brutally killing workers...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/python/flask/cmdb
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:40282)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from cmdb_uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Mon Mar  1 17:15:06 2021] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 08 December 2019 05:05:53
os: Linux-3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019
nodename: fushisanlang.cn
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/python/flask/cmdb
detected binary path: /usr/local/bin/uwsgi
your processes number limit is 6945
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:30005 fd 5
uwsgi socket 0 bound to TCP address 127.0.0.1:40131 (port auto-assigned) fd 4
Python version: 3.6.8 (default, Aug  7 2019, 17:28:10)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x24ce430
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
added /home/python/flask/cmdb/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x24ce430 pid: 839 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 839)
spawned uWSGI worker 1 (pid: 16745, cores: 1)
spawned uWSGI http 1 (pid: 16746)
Mon Mar  1 17:15:15 2021 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
[uWSGI] getting INI configuration from cmdb_uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Mon Mar  1 17:16:12 2021] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 08 December 2019 05:05:53
os: Linux-3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019
nodename: fushisanlang.cn
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/python/flask/cmdb
detected binary path: /usr/local/bin/uwsgi
your processes number limit is 6945
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:30005 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:35253 (port auto-assigned) fd 3
Python version: 3.6.8 (default, Aug  7 2019, 17:28:10)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xf474b0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
added /home/python/flask/cmdb/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xf474b0 pid: 16844 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 16844)
spawned uWSGI worker 1 (pid: 16897, cores: 1)
spawned uWSGI http 1 (pid: 16898)
gateway "uWSGI http 1" has been buried (pid: 16898)
...brutally killing workers...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/python/flask/cmdb
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:35253)
running /usr/local/bin/uwsgi
/usr/local/bin/uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
uwsgi: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
